name: kube-fencing
description: Fencing implementation for Kubernetes
version: 2.0.0
keywords:
  - fencing
  - fence
home: https://github.com/kvaps/kube-fencing
sources:
  - https://hub.docker.com/r/kvaps/kube-fencing-controller
  - https://hub.docker.com/r/kvaps/kube-fencing-switcher
  - https://hub.docker.com/r/kvaps/kube-fencing-agents
maintainers:
  - name: kvaps
    email: kvapss@gmail.com
